//
//  UserModels.swift
//  iOSJustoTest
//
//  Created by Alan Muñoz on 14/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserScene
{
  // MARK: Use cases
  
  enum LoadingData
  {
    struct Request {
    }
    struct Response {
        let users: [User]
    }
      struct ViewModel {
        let users: [User]
    }
  }
}
