//
//  UserInteractor.swift
//  iOSJustoTest
//
//  Created by Alan Muñoz on 14/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserBusinessLogic
{
  func doLoadData(request: UserScene.LoadingData.Request)
}

protocol UserDataStore
{
  //var name: String { get set }
}

class UserInteractor: UserBusinessLogic, UserDataStore
{
  var presenter: UserPresentationLogic?
  var worker: UserWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doLoadData(request: UserScene.LoadingData.Request)
  {
    worker = UserWorker()
 
      worker?.fetchUsers(completionHandler: { users in
          let response = UserScene.LoadingData.Response(users: users)
          self.presenter?.presentData(response: response)
      }, failureCompletion: { error in
          
      })

  }
}
