//
//  UserPresenter.swift
//  iOSJustoTest
//
//  Created by Alan Muñoz on 14/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserPresentationLogic
{
  func presentData(response: UserScene.LoadingData.Response)
}

class UserPresenter: UserPresentationLogic
{
  weak var viewController: UserDisplayLogic?
  
  // MARK: Do something
  
  func presentData(response: UserScene.LoadingData.Response)
  {
      let viewModel = UserScene.LoadingData.ViewModel(users: response.users)
    viewController?.showData(viewModel: viewModel)
  }
}
